import { admin, db, email } from 'hatchable';
export const access='admin'; export const methods=['GET','POST','PUT','DELETE'];
const T='"app_14ce2009b987445c".nexa_content';
const COLS='id,kind,title,description,image_url,release_at,published_at,active,created_at';
async function owner(req,res){const p=await admin.profile(req);if(String(p?.email||'').toLowerCase()==='edoardodalsoggio@gmail.com')return true;res.status(403).json({error:'Forbidden'});return false}
async function notify(x){try{const category=({app:'apps',music:'music',video:'videos',news:'news',project:'projects',event:'events',release:'releases',announcement:'news'}[x.kind]||'news');const [prefs,own]=await Promise.all([db.query('SELECT email FROM notification_preferences WHERE email_enabled=true AND '+category+'=true'),db.query("SELECT notification_email FROM owner_settings WHERE notification_email<>'' ORDER BY updated_at DESC LIMIT 1")]);const recipients=[...new Set([...prefs.rows.map(r=>String(r.email||'').trim().toLowerCase()),...own.rows.map(r=>String(r.notification_email||'').trim().toLowerCase())].filter(Boolean))];for(const to of recipients){try{await email.send({to,subject:'NEXA — '+x.title,text:'Nuovo contenuto disponibile su NEXA Space: '+x.title+'\n\n'+String(x.description||'').replace(/\[\[.*?\]\]/g,''),html:'<h2>'+String(x.title||'NEXA')+'</h2><p>'+String(x.description||'Nuovo contenuto disponibile su NEXA.').replace(/\[\[.*?\]\]/g,'')+'</p><p>Nuovo contenuto disponibile su NEXA Space.</p>'})}catch(e){console.error('email notification failed',e)}}}catch(e){console.error('notification setup failed',e)}}
export default async function(req,res){if(!await owner(req,res))return;try{
if(req.method==='GET'){const r=await db.query('SELECT '+COLS+' FROM '+T+' ORDER BY created_at DESC');res.setHeader('Cache-Control','no-store');return res.json(r.rows||[])}
const b=req.body||{};
if(req.method==='POST'){const r=await db.query('INSERT INTO '+T+' (kind,title,description,image_url,release_at,published_at,active) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING '+COLS,[b.kind||'app',b.title||'NEXA',b.description||'',b.image_url||'',b.release_at||null,b.published_at||new Date().toISOString(),b.active!==false]);const x=r.rows[0];const future=x.release_at&&new Date(x.release_at)>new Date();if(x.active&&!future)await notify(x);return res.json(x)}
if(req.method==='PUT'){const r=await db.query('UPDATE '+T+' SET kind=$1,title=$2,description=$3,image_url=$4,release_at=$5,published_at=$6,active=$7 WHERE id=$8 RETURNING '+COLS,[b.kind,b.title,b.description||'',b.image_url||'',b.release_at||null,b.published_at||new Date().toISOString(),b.active!==false,b.id]);return res.json(r.rows[0]||null)}
await db.query('DELETE FROM '+T+' WHERE id=$1',[b.id]);return res.json({ok:true})
}catch(e){console.error('admin content',e);return res.status(500).json({error:'server_error'})}}